//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueryBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SUN_SCHEMA&gt;
        ///	&lt;row alias=&quot;ICAS&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICAP&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA1&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA2&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA3&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA4&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA5&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA6&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA7&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA8&quot; origin=&quot;CA&quot;/&gt;
        ///	&lt;row alias=&quot;ICA9&quot; origin=&quot;CA&quot;/&gt;
        ///&lt;/SUN_SCHEMA&gt;.
        /// </summary>
        internal static string _ALIAS {
            get {
                return ResourceManager.GetString("_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SUN_SCHEMA&gt;	
        ///&lt;/SUN_SCHEMA&gt;.
        /// </summary>
        internal static string FROM {
            get {
                return ResourceManager.GetString("FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SUN_SCHEMA&gt;	
        ///&lt;/SUN_SCHEMA&gt;.
        /// </summary>
        internal static string SCHEMALIST {
            get {
                return ResourceManager.GetString("SCHEMALIST", resourceCulture);
            }
        }
    }
}
