//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVCDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TVCDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ROOT&gt;
        ///	&lt;ITEM Code=&quot;AGGREGATE&quot; Value=&quot;aggregate(;)&quot;/&gt;
        ///	&lt;ITEM Code=&quot;ARRAY&quot; Value=&quot;array()&quot;/&gt;
        ///	&lt;ITEM Code=&quot;COLUMN PAGE BREAK&quot; Value=&quot;column page break&quot;/&gt;
        ///	&lt;ITEM Code=&quot;DELETE COLUMN&quot; Value=&quot;delete column&quot;/&gt;
        ///	&lt;ITEM Code=&quot;DELETE ROW&quot; Value=&quot;delete row&quot;/&gt;
        ///	&lt;ITEM Code=&quot;IF&quot; Value=&quot;if(;;)&quot;/&gt;
        ///	&lt;ITEM Code=&quot;LIST&quot; Value=&quot;list()&quot;/&gt;
        ///	&lt;ITEM Code=&quot;LOOKUP&quot; Value=&quot;lookup(;;;)&quot;/&gt;
        ///	&lt;ITEM Code=&quot;NUM2ROMAN&quot; Value=&quot;NUM2ROMAN(1)&quot;/&gt;
        ///	&lt;ITEM Code=&quot;NUM2STR&quot; Value=&quot;NUM2ST [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyFunc {
            get {
                return ResourceManager.GetString("MyFunc", resourceCulture);
            }
        }
    }
}
